---
# YAML Linting Configuration

extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Trailing spaces
  trailing-spaces: enable

  # Document start
  document-start:
    present: false

  # Comments
  comments:
    min-spaces-from-content: 1

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

  # Empty values
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true

ignore: |
  .git/
  venv/
  env/
  __pycache__/
  .pytest_cache/
  .mypy_cache/
  .ruff_cache/
  dist/
  build/
